import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body
        className={cn(
          "bg-slate-900 text-slate-100 container p-20",
          inter.className
        )}
      >
        <header>
          <h1 className="text-3xl font-semibold">Dashboard</h1>
        </header>
        <div className="my-10"></div>
        {children}
      </body>
    </html>
  );
}
