import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const revalidate = 0;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pages = [
  { route: "/no-loading", name: "No Loading" },
  { route: "/loading", name: "Loading" },
  { route: "/suspense", name: "Suspense 🥷" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "bg-slate-900 text-slate-100 container p-20",
          inter.className
        )}
      >
        <header className="flex justify-between items-center">
          <h1 className="text-3xl font-semibold">
            <Link href={"/"}>Dashboard</Link>
          </h1>
          <nav className="flex items-center gap-4">
            {pages.map((x) => (
              <Link key={x.route} href={x.route} className="">
                <Button variant="outline">{x.name}</Button>
              </Link>
            ))}
          </nav>
        </header>
        <div className="my-10"></div>
        {children}
      </body>
    </html>
  );
}
